global using AlignH = WellspringCS.Wellspring.HorizontalAlignment;
global using AlignV = WellspringCS.Wellspring.VerticalAlignment;
global using Buffer = MoonWorks.Graphics.Buffer;
global using MoonWorks.Graphics.Font;
global using MoonWorks.Graphics;
global using MoonWorks.Input;
global using MoonWorks.Math.Float;
global using MoonWorks.Math;
global using MoonWorks;
global using MyGame.Aseprite;
global using MyGame.Coroutines;
global using MyGame.Graphics;
global using MyGame.Input;
global using MyGame.Screens;
global using MyGame.TWConsole;
global using MyGame.TWImGui.Inspectors;
global using MyGame.TWImGui;
global using MyGame.Utils;
global using Newtonsoft.Json.Linq;
global using Newtonsoft.Json;
global using Num = System.Numerics;
global using System.Collections.Generic;
global using System.Collections;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Threading.Tasks;
global using System;
global using WellspringCS;
global using ldtk;
