global using ldtk;
global using MoonWorks.Graphics;
global using MoonWorks.Input;
global using MoonWorks.Math.Float;
global using MoonWorks.Math;
global using MoonWorks;
global using MyGame.Aseprite;
global using Num = System.Numerics; 
global using System.Collections.Generic;
global using System.Collections;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Text;
global using System;
